Dev
catalyst-team/neuro pull request #28
Opened 2020-05-10 15:22 UTC by Bekovmi

Increase speed of training

2020-05-10 15:22 UTC, pep8speaks commented
Hello @Bekovmi! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`training/generator_coords.py`](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/generator_coords.py):

> [Line 35:13](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/generator_coords.py#L35): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator





* In the file [`training/runner.py`](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/runner.py):

> [Line 116:33](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/runner.py#L116): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 117:33](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/runner.py#L117): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 118:33](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/runner.py#L118): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 138:33](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/runner.py#L138): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 139:33](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/runner.py#L139): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 140:33](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/runner.py#L140): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 177:13](https://github.com/catalyst-team/neuro/blob/01dfc4d89d5cf2a1a9a9ba18c816126d257a65b3/training/runner.py#L177): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

2020-05-11 05:26 UTC, Scitator requested changes

2020-05-11 05:26 UTC, Scitator commented on neuro/scripts/download_dataset.sh
> +rm brain_data.zip
remove please

2020-05-11 05:26 UTC, Scitator commented on training/reader.py
> +            "/home/Bekovmi/neuro/presets/label_protocol_unique.txt", "r"
return default name please

2020-05-11 05:26 UTC, Scitator commented on training/runner.py
> +class NeuroRunner(Runner):
are you sure you need whole Runner copy-pasted? what would you like to do?

2020-05-11 05:30 UTC, Bekovmi commented on training/runner.py
> +class NeuroRunner(Runner):
Some classes are abstract, I couldn't inherited

2020-05-12 06:41 UTC, Scitator commented on training/runner.py
> +class NeuroRunner(Runner):
could you add some examples of `abstract` classes?

2020-05-12 06:42 UTC, Scitator commented
btw, @Bekovmi could you please fix codestyle?
you can use https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md#codestyle for more info

2020-05-13 06:05 UTC, Bekovmi commented on training/runner.py
> +class NeuroRunner(Runner):
I mix up classes with methods. If I rewrite following methods: _run_batch, _run_loader and add _crop_data, I will receive error with inherited _handle_batch.

2020-05-13 07:27 UTC, Scitator commented on training/runner.py
> +class NeuroRunner(Runner):
what could not you just rewrite `_handle_batch`?

2020-05-13 07:31 UTC, Scitator commented on training/runner.py
> +class NeuroRunner(Runner):
what functionality have you rewrite?

2020-05-13 12:59 UTC, Bekovmi commented on training/runner.py
> +class NeuroRunner(Runner):
new _run_batch with _run_loader

2020-05-14 07:34 UTC, Scitator commented on training/runner.py
> +class NeuroRunner(Runner):
then... why have you copy-paste whole runner? could be redefine only really required parts?

2020-05-14 13:40 UTC, Bekovmi commented on training/runner.py
> +class NeuroRunner(Runner):
Потому что если полностью не скопировать, возникает ошибка.

2020-05-15 09:14 UTC, Scitator commented on training/runner.py
> +class NeuroRunner(Runner):
what error? have you tried to debug?

2020-05-15 09:15 UTC, Scitator requested changes

2020-05-15 09:15 UTC, Scitator commented on training/runner.py
> +    def _crop_data(self, batch, coords):
could you remove this function to dataset?

2020-05-17 18:07 UTC, closed without merging